import { useState, useCallback } from 'react';
import { useGetHeadlines, getGetHeadlinesQueryKey } from '@workspace/api-client-react';
import type { GetHeadlinesCategory } from '@workspace/api-client-react';
import { Header } from '@/components/Header';
import { ArticleGrid } from '@/components/ArticleGrid';
import { useDebounce } from '@/hooks/use-debounce';
import { useQueryClient } from '@tanstack/react-query';

export default function Home() {
  const [searchInput, setSearchInput] = useState('');
  const [activeCategory, setActiveCategory] = useState<GetHeadlinesCategory | 'all'>('all');

  const debouncedSearch = useDebounce(searchInput, 400);
  const queryClient = useQueryClient();

  const params = {
    ...(activeCategory !== 'all' ? { category: activeCategory as GetHeadlinesCategory } : {}),
    ...(debouncedSearch.trim() ? { q: debouncedSearch.trim() } : {}),
    pageSize: 20,
  };

  const { data, isLoading, isError, refetch } = useGetHeadlines(params, {
    query: {
      queryKey: getGetHeadlinesQueryKey(params),
      staleTime: 2 * 60 * 1000, // 2 minutes
    },
  });

  const handleRetry = useCallback(() => {
    queryClient.invalidateQueries({ queryKey: getGetHeadlinesQueryKey(params) });
    refetch();
  }, [queryClient, params, refetch]);

  const handleCategoryChange = useCallback((cat: GetHeadlinesCategory | 'all') => {
    setActiveCategory(cat);
    // Clear search when switching categories for cleaner UX
    setSearchInput('');
  }, []);

  const categoryLabel = activeCategory === 'all' ? 'Top Headlines' : 
    activeCategory.charAt(0).toUpperCase() + activeCategory.slice(1);

  return (
    <div className="min-h-[100dvh] bg-background noise-overlay">
      <Header
        searchQuery={searchInput}
        onSearchChange={setSearchInput}
        activeCategory={activeCategory}
        onCategoryChange={handleCategoryChange}
        totalResults={data?.totalResults}
      />

      <main className="max-w-6xl mx-auto px-4 sm:px-6 py-8">
        {/* Section heading */}
        <div className="flex items-baseline justify-between mb-6">
          <div>
            <h2 className="font-serif-display text-2xl sm:text-3xl font-bold text-foreground">
              {debouncedSearch ? 'Search Results' : categoryLabel}
            </h2>
            <div className="w-12 h-0.5 bg-primary mt-1.5" />
          </div>
          {!isLoading && data?.articles && (
            <span className="text-sm text-muted-foreground">
              {data.articles.length} article{data.articles.length !== 1 ? 's' : ''}
            </span>
          )}
        </div>

        <ArticleGrid
          articles={data?.articles}
          isLoading={isLoading}
          isError={isError}
          searchQuery={debouncedSearch}
          onRetry={handleRetry}
        />
      </main>

      {/* Footer */}
      <footer className="max-w-6xl mx-auto px-4 sm:px-6 py-8 mt-4 border-t border-border/50">
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3">
          <p className="font-serif-display text-sm font-semibold text-muted-foreground">
            AI News Digest
          </p>
          <p className="text-xs text-muted-foreground text-center sm:text-right">
            News powered by NewsAPI. Summaries generated by AI. Always verify with original sources.
          </p>
        </div>
      </footer>
    </div>
  );
}
